Drop O/P: eventum(router)
1. conflicts with rpm 4.16 boolean dependencies
2. the virtual dependency has only one resolution

error: line 243: Illegal char ')' (0x29) in: Obsoletes: eventum(router)